GET http://localhost:6000/
content-type: application/json

###

POST http://localhost:6000/api/upload
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
